---
# Add a network to allow the host and containers to communicate with each other
networks:
  demo_net:
    # Explicitly state the name so Docker does not prepend it with the directory name
    # (e.g., 01-docker-network_demo_net)
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

# Define the containers (services) you want to run
# Each one will be a separate container with its own configuration
services:
  demo_cont_1:
    build:
      context: .
      dockerfile: demo.dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER1_NAME}
    hostname: ${CONTAINER1_NAME}
    networks:
      demo_net:
        ipv4_address: ${CONTAINER1_IPV4}
    ports:
      # Expose on host port 80
      - "${CONTAINER1_PORT}:80"

  demo_cont_2:
    # Reuse image built by demo_cont_1
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER2_NAME}
    hostname: ${CONTAINER2_NAME}
    networks:
      demo_net:
        ipv4_address: ${CONTAINER2_IPV4}

    ports:
      # Expose on host port 80
      - "${CONTAINER2_PORT}:80"
...
# code: language=yaml
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
