pipeline {
    agent {
        any {
            image 'python:3'
        }
    }
    stages {
        stage('build') {
            steps {
                echo "Building ${env.JOB_NAME}..."
                sh 'python3 -m pip install --user Flask'
                sh 'python3 -m pip install --user xmlrunner'
                sh 'cat /etc/os-release'
            }
        }
        stage('test') {
            steps {
                echo "Testing ${env.JOB_NAME}..."
                // Ensure the data.csv file is not corrupted
                sh 'echo "bc1932ebf66ff108fb5ff0a6769f2023a9002c7dafee53d85f14c63cab428b4a  data.csv" | sha256sum -c'
                // Unit test app.py
                sh 'python3 test_app.py'
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }
    }
    post {
        success {
            echo "Good to go!"
        }
        failure {
            echo "Houston, we've had a problem."
        }
    }
}